Feat/text area
PrestaShopCorp/puik pull request #143
Opened 2023-06-22 08:26 UTC by GuillaumeGuerin1

### ❓ Types of changes
Add a textarea component

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Create a text area component

### 📝 Checklist

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-06-27 07:42 UTC, Kelhel requested changes

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/src/textarea.vue
> +        :id="id"
Ta props id n'est pas obligatoire et est par défaut un texte vide, il ne faut pas d'id avec un string vide

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +      description: '',
Il manque la description sur toutes les props

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +</puik-textarea>
```suggestion
<puik-textarea v-bind="args" v-model="value"></puik-textarea>
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +  success: false,
```suggestion
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +      <!--HTML/CSS Snippet-->
```suggestion
<!--VueJS Snippet-->
<puik-textarea
  id="textarea"
  disabled
  v-model="value"
>
</puik-textarea>
      
<!--HTML/CSS Snippet-->
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +  success: false,
```suggestion
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +      <!--VueJS Snippet-->
```suggestion
<!--VueJS Snippet-->
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +      <!--HTML/CSS Snippet-->
```suggestion
<!--HTML/CSS Snippet-->
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +  success: true,
```suggestion
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +      <!--HTML/CSS Snippet-->
```suggestion
<!--HTML/CSS Snippet-->
```

2023-06-27 07:42 UTC, Kelhel commented on packages/components/textarea/stories/textarea.stories.ts
> +  success: false,
```suggestion
```

2023-06-27 07:57 UTC, GuillaumeGuerin1 commented on packages/components/textarea/test/textarea.spec.ts
> +        'onUpdate:modelValue': async (modelValue: any) =>
Non, c'est bien `onUpdate`
https://test-utils.vuejs.org/guide/advanced/v-model.html#a-simple-example

2023-07-03 15:36 UTC, cnavarro-prestashop approved these changes

2023-07-04 09:00 UTC, Kelhel approved these changes

2023-07-05 12:35 UTC, merged