Improvement/button
PrestaShopCorp/puik pull request #177
Opened 2023-08-17 15:08 UTC by mattgoud

### ❓ Types of changes

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [x] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

https://www.notion.so/prestashopcorp/Light-version-of-the-primary-secondary-tertiary-button-for-dark-background-icons-8b849032dd2548cbaded40f91d6298f9?pvs=4 

### 📝 Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-08-21 08:30 UTC, MikeLebeau requested changes

2023-08-21 08:44 UTC, MikeLebeau commented on packages/components/button/src/button.ts
> +export const buttonTheme = ['light', 'dark'] as const
Hm... j'ai pas vu la page notion :O

2023-08-21 08:49 UTC, MikeLebeau commented on packages/components/button/src/button.ts
> +export const buttonTheme = ['light', 'dark'] as const
Alors, du coup je pense pas qu'il nous faut `buttonTheme` je pense que ca va porter a confusion plus tard.

Par contre, il faudrait plutot rajouter un variant `light-primary` (de meme pour les deux autres) ou `dark-primary` je te laisse voir la dessus je suis a chier en naming xD

2023-08-28 15:13 UTC, mattgoud commented on packages/components/button/src/button.ts
> +export const buttonTheme = ['light', 'dark'] as const
hello @MikeLebeau , oui ça risque de porter à confusion pour la suite, j'ai supprimé la prop theme et créer des variants à la place (primary-reverse, secondary-reverse et text-reverse)

2023-08-28 15:13 UTC, mattgoud commented on packages/components/button/src/button.ts
> +export const buttonTheme = ['light', 'dark'] as const
nb : naming des variants vus avec @FrancoisQtr

2023-08-29 11:26 UTC, MikeLebeau approved these changes

2023-08-31 08:07 UTC, cnavarro-prestashop approved these changes

2023-08-31 08:09 UTC, cnavarro-prestashop approved these changes

2023-08-31 08:09 UTC, merged