fix: #232 : puik-link underline on multi-lines
PrestaShopCorp/puik pull request #233
Opened 2023-10-23 15:12 UTC by mattgoud

### ❓ Types of changes
fix : [BUG] puik link decoration underline is fucked up on multi-line 😭 + width 100% not good #232

- [ ] 📖 Documentation (updates to the documentation or readme)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-10-23 15:18 UTC, cnavarro-prestashop approved these changes

2023-10-24 12:31 UTC, MikeLebeau requested changes

2023-10-24 12:31 UTC, MikeLebeau commented on packages/theme/src/link.scss
> +  background-position: left bottom 1.25px;
Ca tu peux le mettre dans la ligne au dessus en tailwind -> `bg-[left_bottom_1.25px]`

2023-10-24 12:31 UTC, MikeLebeau commented on packages/theme/src/link.scss
> +    background-position: left bottom 0px;
Ca tu peux le mettre dans la ligne au dessus en tailwind -> `bg-[left_bottom_0px]`, a voir si besoin de preciser le `0px` 🤔  sinon j'imagine que ca devient `bg-left-bottom`

2023-10-24 13:23 UTC, mattgoud commented on packages/theme/src/link.scss
> +  background-position: left bottom 1.25px;
bien vu ! modif effectuée

2023-10-24 13:23 UTC, mattgoud commented on packages/theme/src/link.scss
> +    background-position: left bottom 0px;
> Ca tu peux le mettre dans la ligne au dessus en tailwind -> `bg-[left_bottom_0px]`, a voir si besoin de preciser le `0px` 🤔 sinon j'imagine que ca devient `bg-left-bottom`

bien vu @MikeLebeau ! modif effectuée

2023-10-24 13:33 UTC, MikeLebeau submitted a review, later dismissed
🚀

2023-10-30 13:55 UTC, kktos approved these changes

2023-10-30 13:56 UTC, merged