Feat -  Add close button to alert component
PrestaShopCorp/puik pull request #236
Opened 2023-10-30 13:36 UTC by aAmorim27

### ❓ Types of changes

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added a close button to the Alert component

:warning: We need this feature before the end of this sprint

### 📝 Checklist

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-10-30 13:40 UTC, cnavarro-prestashop submitted a review, later dismissed

2023-10-30 14:01 UTC, kktos requested changes

2023-10-30 14:01 UTC, kktos commented on packages/components/alert/src/alert.ts
> +  closable: {
you have other components having this property and it's named "isClosable".
Which makes sense as it is a boolean.
And you wish to be coherent amongst the whole lib when naming things ;)

2023-10-31 08:52 UTC, kktos approved these changes

2023-10-31 08:54 UTC, merged