improvement: [chip/tag] fix #225 - use isEllipsis to trigger tooltip
PrestaShopCorp/puik pull request #247
Opened 2023-11-15 21:48 UTC by mattgoud

use isEllipsisIsActive function to trigger tooltip instead of using the length of the content

### ❓ Types of changes

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [ ] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-11-16 16:39 UTC, MikeLebeau requested changes
A par le petit bout de code commenté qui traine c'est good

2023-11-16 16:39 UTC, MikeLebeau commented on packages/theme/src/chip.scss
> +    // }
👀 Beuuuuh du code commenté :p

2023-11-17 16:29 UTC, mattgoud commented on packages/theme/src/chip.scss
> +    // }
yes ! commentaires supprimés @MikeLebeau

2023-11-20 08:16 UTC, MikeLebeau approved these changes

2023-11-22 15:42 UTC, merged