fix: try to fix first parent who don't have a data-test by default
PrestaShopCorp/puik pull request #260
Opened 2023-11-27 18:09 UTC by guillaume60240

## :boom: Warning
**breaking changes on data-test attributes**  

Some components present a problem when they have already been used with a data-test attribute before version 1.8. To correct this, I added a data-test (without adding a prefix) to the first parent of the components that I spotted
### ❓ Types of changes

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
- [ ] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.

2023-11-27 18:22 UTC, guillaume60240 commented
Attention, il y aura un breaking change pour la progress bar afin de respecter la demande d'avoir un data-test sans préfixe sur le premier parent (seul fichier de test modifié)

2023-11-28 07:42 UTC, kktos requested changes
I think you should add a test about this feature.
As a rule of thumb, when a bug is discovered, you add a test in your unit test to check it, you do the fix and you see if the test is passing.
This will help against regressions ;)

2023-11-28 10:41 UTC, mattgoud commented
> I think you should add a test about this feature. As a rule of thumb, when a bug is discovered, you add a test in your unit test to check it, you do the fix and you see if the test is passing. This will help against regressions ;)

ok @kktos, tests relating to the new data-tests created

2023-11-28 10:48 UTC, kktos approved these changes

2023-11-28 11:03 UTC, merged